---
title: "R Notebook"
output: html_notebook
---

```{r load package}
library(dplyr)
library(Seurat)
library(patchwork)
library(multtest)
library(metap)
library(ggplot2)
library(cowplot)
```

```{r check no parallelization}
future::plan("default",.init=FALSE)
future::plan()
```

```{r set parameters}
set.seed(444)
cpu_core = 4 #number of cores for parallelized findallmarkers
curr.wd <- "~/" #curr.wd
tissue <- "cartilage" 
merge <- TRUE #if we want to do merging
integration.technique = "SCTransform"  #"regular" for normal integration workflow


if(!integration.technique %in% c("SCTransform","regular"))
  {message("Invalid integration technique name")}
```

```{r sample names}
if (tissue == "cartilage"){
  folder.name <- "Cartilage_Count_Files"
  #sample.names <- list.dirs(paste0(curr.wd,folder.name),full.names = FALSE, recursive = FALSE) 
  sample.names <- c("AGA2","AgaCg26-3","AgaPCg2-1","AgaPCg2-4","AgaPCg2-6", 
                    "mouse1","mouse2","mouse3","mouse4","mouse5")
  #sample.names <- c("AgaPCg2-4","mouse5")
}

```


```{r load sample function}
load_data <- function(count.data, 
                      project.name, 
                      sample.label = project.name,
                      sample.timepoint = NULL,
                      nFeature_RNA.min = 1000, 
                      nFeature_RNA.max = 5500, 
                      nCount_RNA.max = 50000, 
                      percent.mt.max = 5){
  sample.obj <- Seurat::CreateSeuratObject(count = count.data, project = project.name, min.cells = 3, min.features = 200)
  sample.obj[["percent.mt"]] <- Seurat::PercentageFeatureSet(sample.obj, pattern = "^mt-")
  sample.obj <- subset(sample.obj, subset = nFeature_RNA > nFeature_RNA.min & 
                                                      nFeature_RNA < nFeature_RNA.max & 
                                                      nCount_RNA < nCount_RNA.max & 
                                                      percent.mt < percent.mt.max )
  sample.obj$label <- sample.label
  if(!is.null(sample.timepoint)){
    sample.obj$timepoint <- sample.timepoint
  }
  return (sample.obj)
}
```


```{r create list of seurat object}
#create list of seurat objects
sample.list <- list()
for(ind in seq(1:length(sample.names))){
  read.data <- Seurat::Read10X(data.dir=paste0(curr.wd, folder.name, "/", sample.names[[ind]], "/filtered_feature_bc_matrix/"))

  #load cartilage
  if(tissue == "cartilage"){
    if(grepl("aga", tolower(sample.names[[ind]]), fixed = TRUE) == TRUE){
      sample.list[[ind]] <- load_data(read.data, sample.names[[ind]], 
                                      sample.label = "Aga2", 
                                      nFeature_RNA.max = 7000,
                                      percent.mt.max = 5) ##aga cartilage
    }else{
      sample.list[[ind]] <- load_data(read.data, sample.names[[ind]], 
                                      sample.label = "WT", 
                                      nFeature_RNA.max = 5500,
                                      percent.mt.max = 10) ##wt cartilage
    }
  }
  
```


```{r merge}
if(merge == TRUE){
    sample.merge <- merge(sample.list[[1]], y = sample.list[[-1]], add.cell.ids = sample.names, project = paste0("merged_",tissue))
    
    #visualize
    VlnPlot(sample.merge, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by = "label")
}
```

```{r integrate with sctransform}

if(integration.technique == "SCTransform"){
  #future::plan("multiprocess", workers = cpu_core)

  sample.list <- lapply(X = sample.list, FUN = SCTransform, method = "glmGamPoi") #glmGamPoi improve learning speed
  features <- SelectIntegrationFeatures(object.list = sample.list, nfeatures = 2000)
  sample.list <- PrepSCTIntegration(object.list = sample.list, anchor.features = features)
  sample.list <- lapply(X = sample.list, FUN = RunPCA, features = features)
  
  anchors <- FindIntegrationAnchors(object.list = sample.list, normalization.method = "SCT",
      anchor.features = features, dims = 1:30, reduction = "rpca", k.anchor = 5)
  combined.samples <- IntegrateData(anchorset = anchors, normalization.method = "SCT", dims = 1:30)
  future::plan("default",.init=FALSE)
  future::plan()

}

```

```{r integrate with regular normalization}
if (integration.technique == "regular"){
  if(sctransform == TRUE){
    warning("regular normalization will overwrite SCtransform ")
  }
  future::plan("multiprocess", workers = cpu_core)

  sample.list <- lapply(X = sample.list, FUN = function(x) {
    x <- NormalizeData(x, verbose = FALSE)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
    })
  features <- SelectIntegrationFeatures(object.list = sample.list)
  sample.list <- lapply(X = sample.list, FUN = function(x) {
    x <- ScaleData(x, features = features, verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE)
  })
  anchors <- FindIntegrationAnchors(object.list = sample.list, reduction = "rpca", dims = 1:30)
  sample.list <- IntegrateData(anchorset = anchors, dims = 1:30)
  
  future::plan("default",.init=FALSE)
  future::plan()
}
```

```{r downstream analysis and save object}
combined.samples <- RunPCA(combined.samples, verbose = FALSE)
combined.samples <- RunUMAP(combined.samples, reduction = "pca", dims = 1:30)

combined.samples <- FindNeighbors(combined.samples, dims = 1:30, verbose = FALSE)
combined.samples <- FindClusters(combined.samples, verbose = TRUE)

saveRDS(combined.samples, file = paste0(curr.wd,tissue,"_combined_",integration.technique,".rds"))
```

```{r fig.height = 5, fig.width = 10, fig.align = "center"}
# Visualization
p1 <- DimPlot(lung_combined_SCTransform, reduction = "umap", group.by = "timepoint")
p2 <- DimPlot(lung_combined_SCTransform, label = TRUE, repel = TRUE) + NoLegend()
#p2 <- DimPlot(immune.combined.sct, reduction = "umap", group.by = "seurat_annotations", label = TRUE,
    #repel = TRUE)
p1 + p2

DimPlot(lung_combined_SCTransform, reduction = "umap", split.by = "orig.ident")
```


```{r FindConservedMarkers}
DefaultAssay(combined.samples) <- "RNA"
conserved.markers.list <- list()
for (cluster_ind in seq(1:length(unique(combined.samples@meta.data$seurat_clusters)))-1){
  conserved.markers[[cluster_ind+1]] <- FindConservedMarkers(combined.samples, ident.1 = cluster_ind, grouping.var = "label", verbose = TRUE)
}
```

```{r inspect result of findconservedmarkers}
for (cluster_ind in seq(1:length(unique(combined.samples@meta.data$seurat_clusters)))-1){
  print(paste("cluster",cluster_ind))
  head(conserved.markers[[cluster_ind+1]])
}
```


```{r FindAllMarkers}
#set parallelization 
future::plan("multiprocess", workers = cpu_core)

DefaultAssay(combined.samples) <- "RNA"
combined.markers <- FindAllMarkers(object = combined.samples, 
                          only.pos = TRUE,
                          logfc.threshold = 0.25)  

future::plan("default",.init=FALSE)
future::plan()
View(combined.markers)                                               

```

```{r inspect and save result of findallmarkers}
# Rearrange the columns to be more intuitive
annot.comb.markers <- combined.markers[ , c(6, 7, 2:4, 1, 5)]

# Order the rows by p-adjusted values
annot.comb.markers <- annot.comb.markers %>%
        dplyr::arrange(cluster, p_val_adj)
#save
write.csv(annot.comb.markers, 
          file = paste0(curr.wd,tissue,"_combined_all_markers.csv"), 
          quote = FALSE)

# Extract top 3 markers per cluster
top.comb.markers <- annot.comb.markers %>%
        group_by(cluster) %>%
        top_n(n = 3,
              wt = avg_log2FC)

# Visualize top 5 markers per cluster
View(top.comb.markers)

```

```{r fig.height = 20, fig.width = 16, fig.align = "center"}
# Extract top 1 markers per cluster
top1.comb.markers <- annot.comb.markers %>%
        group_by(cluster) %>%
        top_n(n = 1,
              wt = avg_log2FC)
#View(top1.comb.markers)
FeaturePlot(combined.samples, features = top1.comb.markers$gene, reduction = "umap", min.cutoff = "q9")

```
